name: m3u8test
on: 
  workflow_dispatch:
    inputs:
      url:
        description: 'Environment to run tests against'
        type: string
        required: true
jobs:
  Deployment:
    runs-on: macos-latest # https://github.com/actions/runner-images
    steps:
      - run: brew install ffmpeg
      - name: m3u8
        env:
          M3U8URL: ${{ inputs.url }}
        run: ffmpeg -i $M3U8URL -c copy m3u8.ts
      - name: upload transfer.sh
        run: curl --upload-file ./m3u8.ts https://transfer.sh/m3u8.ts
        continue-on-error: true
      - name: upload oshi.at
        run: curl --upload-file ./m3u8.ts https://oshi.at/m3u8.ts
        continue-on-error: true
      - name: upload tempfile.me
        run: curl --upload-file ./m3u8.ts https://tempfile.me/m3u8.ts
        continue-on-error: true
      - name: Artifact dSYM
        if: ${{ always() }}
        uses: actions/upload-artifact@v4 # https://github.com/actions/upload-artifact
        with:
          name: m3u8.ts
          path: m3u8.ts
